service: import-service

frameworkVersion: '3'

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: 'npm'

package:
    individually: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "arn:aws:s3:::fancy-import-service/*"

functions:
  importProductsFile:
    handler: src/functions/index.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true

  importFileParser:
    handler: src/functions/index.importFileParser
    events:
      - s3:
          bucket: fancy-import-service
          event: s3:ObjectCreated:*
          rules: 
              - prefix: uploaded/
          existing: true
