service: import-service

frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: 'npm'

package:
    individually: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: "arn:aws:s3:::fancy-import-service/*"
        - Effect: "Allow"
          Action:
            - "sqs:*"
          Resource: "arn:aws:sqs:eu-west-1:761984249461:catalogItemsQueue"

functions:
  importProductsFile:
    handler: src/functions/index.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true
          authorizer:
            type: request
            arn: arn:aws:lambda:eu-west-1:761984249461:function:authorization-service-dev-basicAuthorizer

  importFileParser:
    handler: src/functions/index.importFileParser
    events:
      - s3:
          bucket: fancy-import-service
          event: s3:ObjectCreated:*
          rules: 
              - prefix: uploaded/
          existing: true
